// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "Core/PlayFabError.h"
#include "Core/PlayFabEntityDataModels.h"
#include "Core/PlayFabSettings.h"
#include "Interfaces/IHttpRequest.h"
#include "Interfaces/IHttpResponse.h"

namespace PlayFab
{
    class PLAYFAB_API UPlayFabEntityAPI
    {
    public:
        DECLARE_DELEGATE_OneParam(FAbortFileUploadsDelegate, const EntityModels::FAbortFileUploadsResponse&);
        DECLARE_DELEGATE_OneParam(FAcceptGroupApplicationDelegate, const EntityModels::FEmptyResult&);
        DECLARE_DELEGATE_OneParam(FAcceptGroupInvitationDelegate, const EntityModels::FEmptyResult&);
        DECLARE_DELEGATE_OneParam(FAddMembersDelegate, const EntityModels::FEmptyResult&);
        DECLARE_DELEGATE_OneParam(FApplyToGroupDelegate, const EntityModels::FApplyToGroupResponse&);
        DECLARE_DELEGATE_OneParam(FBlockEntityDelegate, const EntityModels::FEmptyResult&);
        DECLARE_DELEGATE_OneParam(FChangeMemberRoleDelegate, const EntityModels::FEmptyResult&);
        DECLARE_DELEGATE_OneParam(FCreateGroupDelegate, const EntityModels::FCreateGroupResponse&);
        DECLARE_DELEGATE_OneParam(FCreateRoleDelegate, const EntityModels::FCreateGroupRoleResponse&);
        DECLARE_DELEGATE_OneParam(FDeleteFilesDelegate, const EntityModels::FDeleteFilesResponse&);
        DECLARE_DELEGATE_OneParam(FDeleteGroupDelegate, const EntityModels::FEmptyResult&);
        DECLARE_DELEGATE_OneParam(FDeleteRoleDelegate, const EntityModels::FEmptyResult&);
        DECLARE_DELEGATE_OneParam(FFinalizeFileUploadsDelegate, const EntityModels::FFinalizeFileUploadsResponse&);
        DECLARE_DELEGATE_OneParam(FGetEntityTokenDelegate, const EntityModels::FGetEntityTokenResponse&);
        DECLARE_DELEGATE_OneParam(FGetFilesDelegate, const EntityModels::FGetFilesResponse&);
        DECLARE_DELEGATE_OneParam(FGetGlobalPolicyDelegate, const EntityModels::FGetGlobalPolicyResponse&);
        DECLARE_DELEGATE_OneParam(FGetGroupDelegate, const EntityModels::FGetGroupResponse&);
        DECLARE_DELEGATE_OneParam(FGetObjectsDelegate, const EntityModels::FGetObjectsResponse&);
        DECLARE_DELEGATE_OneParam(FGetProfileDelegate, const EntityModels::FGetEntityProfileResponse&);
        DECLARE_DELEGATE_OneParam(FGetProfilesDelegate, const EntityModels::FGetEntityProfilesResponse&);
        DECLARE_DELEGATE_OneParam(FInitiateFileUploadsDelegate, const EntityModels::FInitiateFileUploadsResponse&);
        DECLARE_DELEGATE_OneParam(FInviteToGroupDelegate, const EntityModels::FInviteToGroupResponse&);
        DECLARE_DELEGATE_OneParam(FIsMemberDelegate, const EntityModels::FIsMemberResponse&);
        DECLARE_DELEGATE_OneParam(FListGroupApplicationsDelegate, const EntityModels::FListGroupApplicationsResponse&);
        DECLARE_DELEGATE_OneParam(FListGroupBlocksDelegate, const EntityModels::FListGroupBlocksResponse&);
        DECLARE_DELEGATE_OneParam(FListGroupInvitationsDelegate, const EntityModels::FListGroupInvitationsResponse&);
        DECLARE_DELEGATE_OneParam(FListGroupMembersDelegate, const EntityModels::FListGroupMembersResponse&);
        DECLARE_DELEGATE_OneParam(FListMembershipDelegate, const EntityModels::FListMembershipResponse&);
        DECLARE_DELEGATE_OneParam(FListMembershipOpportunitiesDelegate, const EntityModels::FListMembershipOpportunitiesResponse&);
        DECLARE_DELEGATE_OneParam(FRemoveGroupApplicationDelegate, const EntityModels::FEmptyResult&);
        DECLARE_DELEGATE_OneParam(FRemoveGroupInvitationDelegate, const EntityModels::FEmptyResult&);
        DECLARE_DELEGATE_OneParam(FRemoveMembersDelegate, const EntityModels::FEmptyResult&);
        DECLARE_DELEGATE_OneParam(FSetGlobalPolicyDelegate, const EntityModels::FSetGlobalPolicyResponse&);
        DECLARE_DELEGATE_OneParam(FSetObjectsDelegate, const EntityModels::FSetObjectsResponse&);
        DECLARE_DELEGATE_OneParam(FSetProfilePolicyDelegate, const EntityModels::FSetEntityProfilePolicyResponse&);
        DECLARE_DELEGATE_OneParam(FUnblockEntityDelegate, const EntityModels::FEmptyResult&);
        DECLARE_DELEGATE_OneParam(FUpdateGroupDelegate, const EntityModels::FUpdateGroupResponse&);
        DECLARE_DELEGATE_OneParam(FUpdateRoleDelegate, const EntityModels::FUpdateGroupRoleResponse&);

        UPlayFabEntityAPI();
        ~UPlayFabEntityAPI();

        int GetPendingCalls() const;
        FString GetBuildIdentifier() const;
        void SetTitleId(const FString& titleId);
        void SetDevSecretKey(const FString& developerSecretKey);

        // ------------ Generated API calls
        /**
         * Abort pending file uploads to an entity's profile.
         * Aborts the pending upload of the requested files.
         */
        bool AbortFileUploads(EntityModels::FAbortFileUploadsRequest& request, const FAbortFileUploadsDelegate& SuccessDelegate = FAbortFileUploadsDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Accepts an outstanding invitation to to join a group
         * Accepts an outstanding invitation to to join a group if the invited entity is not blocked by the group. Nothing is returned in the case of success.
         */
        bool AcceptGroupApplication(EntityModels::FAcceptGroupApplicationRequest& request, const FAcceptGroupApplicationDelegate& SuccessDelegate = FAcceptGroupApplicationDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Accepts an invitation to join a group
         * Accepts an outstanding invitation to join the group if the invited entity is not blocked by the group. Only the invited entity or a parent in its chain (e.g. title) may accept the invitation on the invited entity's behalf. Nothing is returned in the case of success.
         */
        bool AcceptGroupInvitation(EntityModels::FAcceptGroupInvitationRequest& request, const FAcceptGroupInvitationDelegate& SuccessDelegate = FAcceptGroupInvitationDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Adds members to a group or role.
         * Adds members to a group or role. Existing members of the group will added to roles within the group, but if the user is not already a member of the group, only title claimants may add them to the group, and others must use the group application or invite system to add new members to a group. Returns nothing if successful.
         */
        bool AddMembers(EntityModels::FAddMembersRequest& request, const FAddMembersDelegate& SuccessDelegate = FAddMembersDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Applies to join a group
         * Creates an application to join a group. Calling this while a group application already exists will return the same application instead of an error and will not refresh the time before the application expires. By default, if the entity has an invitation to join the group outstanding, this will accept the invitation to join the group instead and return an error indicating such, rather than creating a duplicate application to join that will need to be cleaned up later. Returns information about the application or an error indicating an invitation was accepted instead.
         */
        bool ApplyToGroup(EntityModels::FApplyToGroupRequest& request, const FApplyToGroupDelegate& SuccessDelegate = FApplyToGroupDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Blocks a list of entities from joining a group.
         * Blocks a list of entities from joining a group. Blocked entities may not create new applications to join, be invited to join, accept an invitation, or have an application accepted. Failure due to being blocked does not clean up existing applications or invitations to the group. No data is returned in the case of success.
         */
        bool BlockEntity(EntityModels::FBlockEntityRequest& request, const FBlockEntityDelegate& SuccessDelegate = FBlockEntityDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Changes the role membership of a list of entities from one role to another.
         * Changes the role membership of a list of entities from one role to another in in a single operation. The destination role must already exist. This is equivalent to adding the entities to the destination role and removing from the origin role. Returns nothing if successful.
         */
        bool ChangeMemberRole(EntityModels::FChangeMemberRoleRequest& request, const FChangeMemberRoleDelegate& SuccessDelegate = FChangeMemberRoleDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Creates a new group.
         * Creates a new group, as well as administration and member roles, based off of a title's group template. Returns information about the group that was created.
         */
        bool CreateGroup(EntityModels::FCreateGroupRequest& request, const FCreateGroupDelegate& SuccessDelegate = FCreateGroupDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Creates a new group role.
         * Creates a new role within an existing group, with no members. Both the role ID and role name must be unique within the group, but the name can be the same as the ID. The role ID is set at creation and cannot be changed. Returns information about the role that was created.
         */
        bool CreateRole(EntityModels::FCreateGroupRoleRequest& request, const FCreateRoleDelegate& SuccessDelegate = FCreateRoleDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Delete files on an entity's profile.
         * Deletes the requested files from the entity's profile.
         */
        bool DeleteFiles(EntityModels::FDeleteFilesRequest& request, const FDeleteFilesDelegate& SuccessDelegate = FDeleteFilesDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Deletes a group and all roles, invitations, join requests, and blocks associated with it.
         * Deletes a group and all roles, invitations, join requests, and blocks associated with it. Permission to delete is only required the group itself to execute this action. The group and data cannot be cannot be recovered once removed, but any abuse reports about the group will remain. No data is returned in the case of success.
         */
        bool DeleteGroup(EntityModels::FDeleteGroupRequest& request, const FDeleteGroupDelegate& SuccessDelegate = FDeleteGroupDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Deletes an existing role in a group.
         * Returns information about the role
         */
        bool DeleteRole(EntityModels::FDeleteRoleRequest& request, const FDeleteRoleDelegate& SuccessDelegate = FDeleteRoleDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Finalize file uploads to an entity's profile.
         * Finalizes the upload of the requested files. Verifies that the files have been successfully uploaded and moves the file pointers from pending to live.
         */
        bool FinalizeFileUploads(EntityModels::FFinalizeFileUploadsRequest& request, const FFinalizeFileUploadsDelegate& SuccessDelegate = FFinalizeFileUploadsDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Method to exchange a legacy AuthenticationTicket or title SecretKey for an Entity Token or to refresh a still valid
         * Entity Token.
         * This API must be called with X-SecretKey, X-Authentication or X-EntityToken headers. An optional EntityKey may be included to attempt to set the resulting EntityToken to a specific entity, however the entity must be a relation of the caller, such as the master_player_account of a character. If sending X-EntityToken the account will be marked as freshly logged in and will issue a new token. If using X-Authentication or X-EntityToken the header must still be valid and cannot be expired or revoked.
         */
        bool GetEntityToken(EntityModels::FGetEntityTokenRequest& request, const FGetEntityTokenDelegate& SuccessDelegate = FGetEntityTokenDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Retrieves file metadata from an entity's profile.
         * Returns URLs that may be used to download the files for a profile for a limited length of time. Only returns files that have been successfully uploaded, files that are still pending will either return the old value, if it exists, or nothing. 
         */
        bool GetFiles(EntityModels::FGetFilesRequest& request, const FGetFilesDelegate& SuccessDelegate = FGetFilesDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Gets the global title access policy
         * Retrieves the title access policy that is used before the profile's policy is inspected during a request. If never customized this will return the default starter policy built by PlayFab.
         */

        bool GetGlobalPolicy(const FGetGlobalPolicyDelegate& SuccessDelegate = FGetGlobalPolicyDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Gets information about a group and its roles
         * Returns the ID, name, role list and other non-membership related information about a group.
         */
        bool GetGroup(EntityModels::FGetGroupRequest& request, const FGetGroupDelegate& SuccessDelegate = FGetGroupDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Retrieves objects from an entity's profile.
         * Gets JSON objects from an entity profile and returns it. 
         */
        bool GetObjects(EntityModels::FGetObjectsRequest& request, const FGetObjectsDelegate& SuccessDelegate = FGetObjectsDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Retrieves the entity's profile.
         * Given an entity type and entity identifier will retrieve the profile from the entity store. If the profile being retrieved is the caller's, then the read operation is consistent, if not it is an inconsistent read. An inconsistent read means that we do not guarantee all committed writes have occurred before reading the profile, allowing for a stale read. If consistency is important the Version Number on the result can be used to compare which version of the profile any reader has.
         */
        bool GetProfile(EntityModels::FGetEntityProfileRequest& request, const FGetProfileDelegate& SuccessDelegate = FGetProfileDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Retrieves the entity's profile.
         * Given a set of entity types and entity identifiers will retrieve all readable profiles properties for the caller. Profiles that the caller is not allowed to read will silently not be included in the results.
         */
        bool GetProfiles(EntityModels::FGetEntityProfilesRequest& request, const FGetProfilesDelegate& SuccessDelegate = FGetProfilesDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Initiates file uploads to an entity's profile.
         * Returns URLs that may be used to upload the files for a profile 5 minutes. After using the upload calls FinalizeFileUploads must be called to move the file status from pending to live.
         */
        bool InitiateFileUploads(EntityModels::FInitiateFileUploadsRequest& request, const FInitiateFileUploadsDelegate& SuccessDelegate = FInitiateFileUploadsDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Invites a player to join a group
         * Invites a player to join a group, if they are not blocked by the group. An optional role can be provided to automatically assign the player to the role if they accept the invitation. By default, if the entity has an application to the group outstanding, this will accept the application instead and return an error indicating such, rather than creating a duplicate invitation to join that will need to be cleaned up later. Returns information about the new invitation or an error indicating an existing application to join was accepted.
         */
        bool InviteToGroup(EntityModels::FInviteToGroupRequest& request, const FInviteToGroupDelegate& SuccessDelegate = FInviteToGroupDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Checks to see if an entity is a member of a group or role within the group
         * Checks to see if an entity is a member of a group or role within the group. A result indicating if the entity is a member of the group is returned, or a permission error if the caller does not have permission to read the group's member list.
         */
        bool IsMember(EntityModels::FIsMemberRequest& request, const FIsMemberDelegate& SuccessDelegate = FIsMemberDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Lists all outstanding requests to join a group
         * Lists all outstanding requests to join a group. Returns a list of all requests to join, as well as when the request will expire. To get the group applications for a specific entity, use ListMembershipOpportunities.
         */
        bool ListGroupApplications(EntityModels::FListGroupApplicationsRequest& request, const FListGroupApplicationsDelegate& SuccessDelegate = FListGroupApplicationsDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Lists all entities blocked from joining a group
         * Lists all entities blocked from joining a group. A list of blocked entities is returned
         */
        bool ListGroupBlocks(EntityModels::FListGroupBlocksRequest& request, const FListGroupBlocksDelegate& SuccessDelegate = FListGroupBlocksDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Lists all outstanding invitations for a group
         * Lists all outstanding invitations for a group. Returns a list of entities that have been invited, as well as when the invitation will expire. To get the group invitations for a specific entity, use ListMembershipOpportunities.
         */
        bool ListGroupInvitations(EntityModels::FListGroupInvitationsRequest& request, const FListGroupInvitationsDelegate& SuccessDelegate = FListGroupInvitationsDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Lists all members for a group
         * Gets a list of members and the roles they belong to within the group. If the caller does not have permission to view the role, and the member is in no other role, the member is not displayed. Returns a list of entities that are members of the group.
         */
        bool ListGroupMembers(EntityModels::FListGroupMembersRequest& request, const FListGroupMembersDelegate& SuccessDelegate = FListGroupMembersDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Lists all groups and roles for an entity
         * Lists the groups and roles that an entity is a part of, checking to see if group and role metadata and memberships should be visible to the caller. If the entity is not in any roles that are visible to the caller, the group is not returned in the results, even if the caller otherwise has permission to see that the entity is a member of that group.
         */
        bool ListMembership(EntityModels::FListMembershipRequest& request, const FListMembershipDelegate& SuccessDelegate = FListMembershipDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Lists all outstanding invitations and group applications for an entity
         * Lists all outstanding group applications and invitations for an entity. Anyone may call this for any entity, but data will only be returned for the entity or a parent of that entity. To list invitations or applications for a group to check if a player is trying to join, use ListGroupInvitations and ListGroupApplications.
         */
        bool ListMembershipOpportunities(EntityModels::FListMembershipOpportunitiesRequest& request, const FListMembershipOpportunitiesDelegate& SuccessDelegate = FListMembershipOpportunitiesDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Removes an application to join a group
         * Removes an existing application to join the group. This is used for both rejection of an application as well as withdrawing an application. The applying entity or a parent in its chain (e.g. title) may withdraw the application, and any caller with appropriate access in the group may reject an application. No data is returned in the case of success.
         */
        bool RemoveGroupApplication(EntityModels::FRemoveGroupApplicationRequest& request, const FRemoveGroupApplicationDelegate& SuccessDelegate = FRemoveGroupApplicationDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Removes an invitation join a group
         * Removes an existing invitation to join the group. This is used for both rejection of an invitation as well as rescinding an invitation. The invited entity or a parent in its chain (e.g. title) may reject the invitation by calling this method, and any caller with appropriate access in the group may rescind an invitation. No data is returned in the case of success.
         */
        bool RemoveGroupInvitation(EntityModels::FRemoveGroupInvitationRequest& request, const FRemoveGroupInvitationDelegate& SuccessDelegate = FRemoveGroupInvitationDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Removes members from a group.
         * Removes members from a group. A member can always remove themselves from a group, regardless of permissions. Returns nothing if successful.
         */
        bool RemoveMembers(EntityModels::FRemoveMembersRequest& request, const FRemoveMembersDelegate& SuccessDelegate = FRemoveMembersDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Sets the global title access policy
         * Updates the title access policy that is used before the profile's policy is inspected during a request. Policies are compiled and cached for several minutes so an update here may not be reflected in behavior for a short time.
         */
        bool SetGlobalPolicy(EntityModels::FSetGlobalPolicyRequest& request, const FSetGlobalPolicyDelegate& SuccessDelegate = FSetGlobalPolicyDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Sets objects on an entity's profile.
         * Sets JSON objects on the requested entity profile. May include a version number to be used to perform optimistic concurrency operations during update. If the current version differs from the version in the request the request will be ignored. If no version is set on the request then the value will always be updated if the values differ. Using the version value does not guarantee a write though, ConcurrentEditError may still occur if multiple clients are attempting to update the same profile. 
         */
        bool SetObjects(EntityModels::FSetObjectsRequest& request, const FSetObjectsDelegate& SuccessDelegate = FSetObjectsDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Sets the profiles access policy
         * This will set the access policy statements on the given entity profile. This is not additive, any existing statements will be replaced with the statements in this request.
         */
        bool SetProfilePolicy(EntityModels::FSetEntityProfilePolicyRequest& request, const FSetProfilePolicyDelegate& SuccessDelegate = FSetProfilePolicyDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Unblocks a list of entities from joining a group
         * Unblocks a list of entities from joining a group. No data is returned in the case of success.
         */
        bool UnblockEntity(EntityModels::FUnblockEntityRequest& request, const FUnblockEntityDelegate& SuccessDelegate = FUnblockEntityDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Updates non-membership data about a group.
         * Updates data about a group, such as the name or default member role. Returns information about whether the update was successful. Only title claimants may modify the administration role for a group.
         */
        bool UpdateGroup(EntityModels::FUpdateGroupRequest& request, const FUpdateGroupDelegate& SuccessDelegate = FUpdateGroupDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());
        /**
         * Updates metadata about a role.
         * Updates the role name. Returns information about whether the update was successful.
         */
        bool UpdateRole(EntityModels::FUpdateGroupRoleRequest& request, const FUpdateRoleDelegate& SuccessDelegate = FUpdateRoleDelegate(), const FPlayFabErrorDelegate& ErrorDelegate = FPlayFabErrorDelegate());

    private:
        // ------------ Generated result handlers
        void OnAbortFileUploadsResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FAbortFileUploadsDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnAcceptGroupApplicationResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FAcceptGroupApplicationDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnAcceptGroupInvitationResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FAcceptGroupInvitationDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnAddMembersResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FAddMembersDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnApplyToGroupResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FApplyToGroupDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnBlockEntityResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FBlockEntityDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnChangeMemberRoleResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FChangeMemberRoleDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnCreateGroupResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCreateGroupDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnCreateRoleResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FCreateRoleDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnDeleteFilesResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FDeleteFilesDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnDeleteGroupResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FDeleteGroupDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnDeleteRoleResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FDeleteRoleDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnFinalizeFileUploadsResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FFinalizeFileUploadsDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnGetEntityTokenResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetEntityTokenDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnGetFilesResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetFilesDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnGetGlobalPolicyResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetGlobalPolicyDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnGetGroupResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetGroupDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnGetObjectsResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetObjectsDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnGetProfileResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetProfileDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnGetProfilesResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FGetProfilesDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnInitiateFileUploadsResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FInitiateFileUploadsDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnInviteToGroupResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FInviteToGroupDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnIsMemberResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FIsMemberDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnListGroupApplicationsResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListGroupApplicationsDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnListGroupBlocksResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListGroupBlocksDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnListGroupInvitationsResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListGroupInvitationsDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnListGroupMembersResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListGroupMembersDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnListMembershipResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListMembershipDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnListMembershipOpportunitiesResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FListMembershipOpportunitiesDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnRemoveGroupApplicationResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FRemoveGroupApplicationDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnRemoveGroupInvitationResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FRemoveGroupInvitationDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnRemoveMembersResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FRemoveMembersDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnSetGlobalPolicyResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSetGlobalPolicyDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnSetObjectsResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSetObjectsDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnSetProfilePolicyResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSetProfilePolicyDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnUnblockEntityResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUnblockEntityDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnUpdateGroupResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUpdateGroupDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);
        void OnUpdateRoleResult(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FUpdateRoleDelegate SuccessDelegate, FPlayFabErrorDelegate ErrorDelegate);

    };
};
